### ISSUE TITLE
Middleware from constructor not show correctly?

### ISSUE THREAD

**Issue by donnygunawan93** [garygreen/pretty-routes#12]
this library doesn't showing middleware tag from constructor?

**Comment by garygreen** [comment]
What do you mean?

**Comment by donnygunawan93** [comment]
for example I have

routes\api.php
`Route::get('example', 'ExampleController@example');`

ExampleController.php
`public function __construct()
    {
        $this->middleware('manager');
    }`

http://localhost:8000/routes just told me ExampleController@example only have middleware api, so where manager middleware?
![untitled](https://cloud.githubusercontent.com/assets/10414213/19188198/56c8ad2c-8cba-11e6-8a2b-013cc8576657.png)

**Comment by garygreen** [comment]
Try changing it to:

``` php
public function __construct()
{
   $this->middleware('manager');
   parent::__construct(); // Add this.
}
```

If that doesn't work your best off asking on laracasts forum or stackoverflow. This package only shows the actual middleware registered with the routes so there must be something not quite right with the way your registering them.

**Comment by donnygunawan93** [comment]
Ok I add parent::construct(); But still same. And **/routes** result is different with the **artisan-cli**.
![one](https://cloud.githubusercontent.com/assets/10414213/19189057/0ea2f948-8cc0-11e6-802b-4c7e7ebeaa06.png)
![two](https://cloud.githubusercontent.com/assets/10414213/19189061/10dfeb26-8cc0-11e6-820d-0441c8bf3fff.png)
this lib only can read Middleware when we type on routes/api.php? can't read when we type on constructor?

**Comment by donnygunawan93** [comment]
It's work only when I use on routes/api.php
`Route::get('example', 'ExampleController@index')->middleware('manager');`
![3rd](https://cloud.githubusercontent.com/assets/10414213/19189267/39a834ae-8cc1-11e6-962b-78811960b8c7.png)

**Comment by garygreen** [comment]
Ahh I see. Well that's a bit an oversight, Laravel's internal route:list command will spin thru all the controllers and add the additional dynamic middlewares.

It would be nice if laravel had a `Route::mergeControllerMiddlewares()` function which could be used. A lot of code seems to be duplicated in RouteListCommand that imo shouldn't be in there. Anyway I'll get round to fixing this soon :)

**Comment by garygreen** [comment]
Composer update and you'll have the fix. Thanks for reporting :)

**Comment by donnygunawan93** [comment]
Woah Thx.
