### ISSUE TITLE
You may want to create a desktop app for it.

### ISSUE THREAD

**Issue by imanghafoori1** [garygreen/pretty-routes#18]
You may want to create a desktop app over the current command-line tool using:
https://github.com/Talesoft/php-gui
but the current state of this package is already fine.

**Comment by garygreen** [comment]
In all honesty, I don't see the purpose in that library now things like Electron exists. Also I'm not sure adding an external desktop app would even make sense - would it be like a routes manager where you can add your apps and you toggle what app's routes you want displayed? How would it work for people who develop on a remote machine? Doesn't make sense to me, sorry
