### ISSUE TITLE
Add cookie to response exception

### ISSUE THREAD

**Issue by Piterden** [garygreen/pretty-routes#20]
I have tried to use pretty routes with PyroCMS. It's almost native Laravel and other soft for Laravel works fine with it.

I have caught an exception:

Please, rename file to .html and open in browser.

**Comment by garygreen** [comment]
This error doesn't look related to pretty routes, maybe something else going on with pyrocms/your install.

PS - I've removed the html you linked to, it contained your username and database password env values, whoops! 😄

**Comment by Piterden** [comment]
If I'll write issue to PyroCMS thread that guy will tell me - "It's pretty routes error, man!"

Can you only presume what makes the problem? Why there's no cookie in response. Laravel needs that cookie too. I had used many custom soft with this stack (including soft which creates new routes and uses middlewares), and no one of it don't call such problems.

PS. Thanks that you were honest and couldn't use this info in your cunning to. But I suppose you will fail with this. Sometimes I have difficulty with access to DB myself:smile:
If serious, I give you even more info about this server:
```term
den:~ $ nmap -A 85.143.212.31

Starting Nmap 7.12 ( https://nmap.org ) at 2017-01-31 19:27 MSK
Nmap scan report for 131143.simplecloud.club (85.143.212.31)
Host is up (0.021s latency).
Not shown: 997 filtered ports
PORT    STATE SERVICE  VERSION
22/tcp  open  ssh      OpenSSH 7.2p2 Ubuntu 4ubuntu2.1 (Ubuntu Linux; protocol 2.0)
| ssh-hostkey: 
|   2048 c7:76:c1:01:89:4a:c9:e3:39:4e:5e:c4:5d:4c:e1:cb (RSA)
|_  256 47:74:42:ca:11:bb:48:84:2f:5f:b9:e6:07:5b:78:f7 (ECDSA)
80/tcp  open  http     nginx
|_http-server-header: nginx
|_http-title: Did not follow redirect to https://131143.simplecloud.club/
443/tcp open  ssl/http nginx
|_http-server-header: nginx
|_http-title: Site doesn't have a title (text/html; charset=UTF-8).
| ssl-cert: Subject: commonName=apex.web812.pro
| Not valid before: 2016-11-30T01:56:00
|_Not valid after:  2017-02-28T01:56:00
|_ssl-date: TLS randomness does not represent time
| tls-nextprotoneg: 
|_  http/1.1
Service Info: OS: Linux; CPE: cpe:/o:linux:linux_kernel

Service detection performed. Please report any incorrect results at https://nmap.org/submit/ .
Nmap done: 1 IP address (1 host up) scanned in 20.59 seconds
```
But you are absolutely right - next time I'd be more careful with credential like this.

**Comment by garygreen** [comment]
Lol your a pretty funny guy. I have no intention to hack into your server :trollface: Though as for the error, nobody else has reported such a problem and there is no mention of pretty routes in the stack trace error, for this moment I can only say it's likely something with your install
