### ISSUE TITLE
Feature request: show file where route is defined

### ISSUE THREAD

**Issue by tnorthcutt** [garygreen/pretty-routes#21]
With a lot of routes, it would be handy to be able to easily see where a route is defined. I'm not sure if that's possible in this package, but if so it'd be pretty slick. The screen would be pretty cluttered as is, so perhaps a tooltip/title tag to display this would make sense.

If you think this is a good idea, and can point me in the right direction, I'd be happy to take a crack at a PR for it.

**Comment by tnorthcutt** [comment]
Ah, nevermind - shoulda dug into the `RouteCollection` object a bit more first; looks like it doesn't include the file where the route is defined.

**Comment by garygreen** [comment]
It maybe possible to do, though. I'm thinking something along the lines of inside your RouteServiceProvider have a `$this->loadRoutesFromFile(....)` and in that function it could call an event "routeFileLoaded" or something, and pretty routes could listen for that and know where each route is registered, technically. Do you really have that many routes files, though? 😄

**Comment by garygreen** [comment]
Also - if your suggesting a way of knowing what line a route was defined on, well that would be pretty cool but a bit more tricky because of route grouping, resource controllers, etc.

**Comment by tnorthcutt** [comment]
"Do you really have that many routes files, though?" nah, just thought it'd be convenient 😉
