### ISSUE TITLE
Want to contribute, don't know how to proceed...

### ISSUE THREAD

**Issue by pebbo** [garygreen/pretty-routes#25]
Hi, I have an idea which I want to try out (and create a pull-request afterwards maybe). But I'm not sure, how to do this. If I fork your project, how can I get it into another Laravel project to see my changes in action? Do I have to put it to packagists? Please help me out? :)

**Comment by Jeroen-G** [comment]
You can clone your fork with git into a Laravel installation, in the vendor folder for example and work on it there.

What I often do is [use the package](https://github.com/Jeroen-G/laravel-packager) I created to work on packages. In this case the command `artisan packager:git` would install your fork and allow to work on a PR from within Laravel.

**Comment by pebbo** [comment]
will try check both options, thank you :)
