### ISSUE TITLE
Doesn't work at all

### ISSUE THREAD

**Issue by ichuprov** [garygreen/pretty-routes#8]
I've followed the installation instructions, but nothing happens (composer goes through fine, I've added the entry to the providers array).
I don't think the package itself is getting registered with laravel (as a test I put a simple Log command which never gets called in any of the code relating to this).
When I run the vendor publish command, nothing happens (ie gives message: Nothing to publish for tag [].)
Am I missing something?
EDIT: using Laravel 5.1

**Comment by garygreen** [comment]
Try deleting bootstrap/cache/compiled.php

**Comment by ichuprov** [comment]
There's no compiled.php file at that location

**Comment by garygreen** [comment]
Other than clearing all your cache stuff `services.json`/`services.php`, `compiled.php` etc I'm honestly not too sure. Sounds like it's not even hitting the service provider. Have you tried it on a clean laravel install?

**Comment by ichuprov** [comment]
I'll try removing the package and reinstalling it. It's very strange. First time I've encountered a package not loading up

**Comment by ichuprov** [comment]
After reinstall - no difference. I put in a dd('pretty routes'); in the boot function. It never hits it. Very bizarre.

**Comment by ichuprov** [comment]
Ok I just worked it out! It was the config cache! I cleared that, and it picked up pretty routes.
